devsearch/devsearch/urls.py
from os import stat
from django.contrib import admin
from django.urls import path, include 

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # include URL from projects app
    path('projects/', include('projects.urls')),
    # include URL from users app
    path('', include('users.urls'))

]

#path to images 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

devsearch/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/',views.loginUser, name='login'),
    path('logout/',views.logoutUser, name='logout'),
    path('register/',views.registerUser, name='register'),
    
    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>/',views.userProfile, name='user-profile'),

]

devsearch/projects/models.py
from django.db import models
import uuid
from users.models import Profile
from django.db.models.base import Model
# Create your models here.

class Project(models.Model):
    # one to one mapping with users app model
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default="default.jpg")
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    # many to many relationship. 'Tag' is in quotes as it was defined later
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title

class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote')
    )
    #owner = 
    # one to many relationship 
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.value

class Tag(models.Model):
    # many to many relation will be defined at source i.e. project
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name

devsearch/users/models.py
from django.db import models
import uuid
# import build in django user model 
from django.contrib.auth.models import User



# Create your models here.
class Profile(models.Model):
    # one to one mapping with django admin user model 
    # on deletion of Django default auth model user associated users in our user app model should also be deleted 
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    short_intro = models.CharField(max_length=500, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to='profiles/', default='profiles/user-default.png')
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)
    social_linkedin = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self) -> str:
        #return str(self.user.username)
        return str(self.username)

class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self) -> str:
        return str(self.name)

devsearch/users/forms.py
from django.contrib.auth import models
from django.db.models import fields
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = {
            'first_name': 'Name'
        }

devsearch/users/views.py
from django.http import request
from django.shortcuts import render, redirect
# login, auth and logout method for django default user database
from django.contrib.auth import login, authenticate, logout
# decorator for login required 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Profile

# importing django auto register and login form.
#from django.contrib.auth.forms import UserCreationForm
# importing custom form.py created for user creation 
from .forms import CustomUserCreationForm

#flash messages to be displayed once
from django.contrib import messages

# Create your views here.


def loginUser(request):
    page = 'login'
    context = {'page': page}
    if request.user.is_authenticated:
        return redirect('profiles')
    
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Username does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('profiles')
        else:
            messages.error(request,'Username/Password is incorrect')

    return render(request, 'users/login_register.html', context)

def logoutUser(request):
    logout(request)
    messages.error(request,'Username successfully logged out')
    return redirect('login')

def registerUser(request):
    page = 'register'
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()

            messages.success(request, 'User account is created')
            login(request, user)
            return redirect('profiles')
        else:
            messages.error(request, 'error while registration')

    context = {'page': page, 'form': form}
    return render(request, 'users/login_register.html', context)

def profiles(request):
    profiles = Profile.objects.all()
    context = {'profiles': profiles}
    return render(request, 'users/profiles.html', context) 

def userProfile(request, pk):
    profile = Profile.objects.get(id=pk)

    # skills that have a description
    topSkills = profile.skill_set.exclude(description__exact="")

    # skills that don't have a description 
    otherSkills = profile.skill_set.filter(description="")

    context = {'profile': profile, 'topSkills':topSkills, 'otherSkills':otherSkills}
    return render(request, 'users/user-profile.html', context) 

devsearch/users/templates/users/login_register.html
{% extends 'mainTemplate.html' %}

{% block content %}
{% if page == 'register' %}

    <h1> Register User </h1>
    <form method="POST" action="{% url 'register' %}">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Register User"/>
    </form>

    <p>Already have an account. <a href="{% url 'login' %}">Login</a> </p>

{% else %}

<form action="{% url 'login' %}" method="POST">
    {% csrf_token %}
    <br/>
    <input type="text" name="username" placeholder="Username"/>
    <br/>
    <input type="password" name="password" placeholder="Enter Password"/>
    <br/>
    <br/>
    <input type="submit" value="Login" />
    <br/>
    <p>Don't have an account. <a href="{% url 'register' %}">Sign Up</a> </p>
</form>
{% endif %}

{% endblock content %}

devsearch/users/templates/users/profiles.html
{% extends 'mainTemplate.html' %}

{% block content %}
    <!-- <h1>Users Profile</h1> -->

    <!-- Main Section -->
  <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <!-- <h2>FROM AROUND THE WORLD</h2> -->
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">
        {% for profile in profiles %}
          <div class="column card">
            <div class="dev">
              <a href="{% url 'user-profile' profile.id %}" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="{{ profile.profile_image.url }}" alt="image" />
                  <div class="dev__meta">
                    <h3>{{profile.name}}</h3>
                    <h5>{{profile.short_intro|slice:"60"}}</h5>
                  </div>
                </div>
                <p class="dev__info">
                <!--Trim the below paragraph to 150 characters -->
                  {{profile.bio|slice:"150"}}
                </p>
                <div class="dev__skills">
                  {% for skill in profile.skill_set.all|slice:'5' %}
                  <span class="tag tag--pill tag--main">
                    <small>{{skill}}</small>
                  </span>
                  {% endfor %}
                </div>
              </a>
            </div>
          </div>
        {% endfor %}
        </div>
      </div>
    </section>

    <!-- <div class="pagination">
      <ul class="container">
        <li><a href="#" class="btn btn--disabled">&#10094; Prev</a></li>
        <li><a href="#" class="btn btn--sub">01</a></li>
        <li><a href="#" class="btn">02</a></li>
        <li><a href="#" class="btn">03</a></li>
        <li><a href="#" class="btn">04</a></li>
        <li><a href="#" class="btn">05</a></li>
        <li><a href="#" class="btn">06</a></li>
        <li><a href="#" class="btn">07</a></li>
        <li><a href="#" class="btn">08</a></li>
        <li><a href="#" class="btn">09</a></li>
        <li><a href="#" class="btn">10</a></li>
        <li><a href="#" class="btn">Next &#10095;</a></li>
      </ul>
    </div> -->
  </main>
{% endblock content %}

devsearch/users/templates/users/user-profile.html
{% extends 'mainTemplate.html' %}

{% block content %}

  <!-- Main Section -->
  <main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">{{profile.location}}</p>
              <ul class="dev__social">
                
                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}
                {% if profile.social_stack %}
                <li>
                  <a title="Stackoverflow" href="{{profile.social_stack}}" target="_blank"><i class="im im-stackoverflow"></i></a>
                </li>
                {%endif%}
                {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}
                {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}
                {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %}
              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
                {{profile.bio}}
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
            
            {% for skill in topSkills %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{skill.name}}</h4>
                <p class="devSkill__info">
                  {{skill.description}}
                </p>
              </div>
            {% endfor %}

              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
                {% for skill in otherSkills %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{skill.name}}</small>
                </span>
                {%endfor%}
              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">
              
              {% for project in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'project' project.id %}" class="project">
                    <img class="project__thumbnail" src="{{project.featured_image.url}}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{project.title}}</h3>
                      {% if p.owner.id %}
                      <p><a class="project__author" href="{% url 'user-profile' project.owner.id %}">By {{project.owner.name}}</a></p>
                      {% endif %}
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Postitive
                        Feedback ({{project.vote_total}} Vote{{project.vote_total|pluralize:"s"}})
                      </p>
                      <div class="project__tags">
                        {% for tag in project.tags.all %}
                        <span class="tag tag--pill tag--main">
                          <small>{{tag}}</small>
                        </span>
                        {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>
              {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

{% endblock content %}